security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"

    role_hierarchy:
        ROLE_MODERATOR: ROLE_USER
        ROLE_ADMIN: [ROLE_MODERATOR, ROLE_USER]

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js|build)/
            security: false

        main:
            lazy: true
            provider: app_user_provider

            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true

            logout:
                path: app_logout
                target: home

            login_throttling:
                max_attempts: 5

    access_control:
        # Public
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }
        - { path: ^/$, roles: PUBLIC_ACCESS }
        - { path: ^/posts$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/posts/\d+$, roles: PUBLIC_ACCESS, methods: [GET] }
        - { path: ^/posts/\d+/vote/, roles: PUBLIC_ACCESS }

        # Posts management
        - { path: ^/posts/new$, roles: ROLE_USER }
        - { path: ^/posts$, roles: ROLE_USER, methods: [POST] }
        - { path: ^/posts/\d+/edit$, roles: ROLE_USER }
        - {
              path: ^/posts/\d+/delete$,
              roles: ROLE_USER,
              methods: [POST, DELETE],
          }

        # Comments management
        - { path: ^/posts/\d+/comment$, roles: ROLE_USER, methods: [POST] }
        - {
              path: ^/comments/\d+/delete$,
              roles: ROLE_USER,
              methods: [POST, DELETE],
          }

        # Moderation
        - { path: ^/moderation, roles: ROLE_MODERATOR }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
